name: NiceSMPArmorTrims
version: 1.0.0
main: com.nicesmp.armortrims.ArmorTrimsPlugin
api-version: '1.21'
description: Functional Armor Trims for Nice SMP - server side only
author: NiceSMP
website: discord.gg/mZfuP5Fkw9

depend: []
softdepend: []
